# Generated by Django 4.1 on 2022-09-09 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('dish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chef.chef')),
            ],
        ),
    ]
